version: "3"
services:
  lunch-db:
    image: mysql:5.7.17
    container_name: siteminder-db
    ports:
      - 3306:3306
    volumes:
      - mysqldata:/var/lib/lunch
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=siteminder
      - MYSQL_DATABASE=siteminder
volumes:
  mysqldata:
    external: false